[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
regex = "1.12.2"
took = "0.1.2"

[profile.release]
strip = true
opt-level = 2
lto = true
